# Site settings
title: blog.sangv2.com
position: Ruby on Rails Developer
description: >-
  Nơi chia sẻ các bài viết về kĩ thuật, kinh nghiệm làm việc của bản thân.
baseurl: ""
url: "https://blog.sangv2.com"

# Author settings
author:
  name: Sang Vo
  url: https://blog.sangv2.com
  email: sangvo111@gmail.com
  position: Ruby on Rails Developer
  description: >-
    Hi, I'm Sang. I'm based in Da Nang, currently work as a Backend Engineer at Sun*.
  twitter_username: sangvo111
  github_username: sangvo

twitter:
  username: sangvo111
  card: summary

facebook:
  app_id: 1412113735801560
  publisher: 100449835536619
  admins: 100002802203533

webmaster_verifications:
  google: -CRD7q2dNtDkGs0m9EFrG1orPG6WVXRIhkFCf8cje44
  bing: F47DE4DEDF75E8647C9F7D9C105AC830

social:
  name: Sang Vo
  links:
    - https://twitter.com/sangvo111
    - https://www.facebook.com/sangvo.dev
    - https://www.linkedin.com/in/sangvo97
    - https://github.com/sangvo

analytics:
  google: G-ER0CVYRKLM
  facebook: 1412113735801560

# Disqus Comments
disqus:
  shortname: sangv2
# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jemoji
  - inline_highlight

include:
  - _pages
  - tag

# Permalinks
permalink: /posts/:title:output_ext
paginate: 5
paginate_path: /page:num/

# Assets
sass:
  sass_dir: _sass
  style: compressed

navigation:
  - name: Home
    link: /
  - name: Articles
    link: /articles/
  - name: About me
    link: /about/
  - name: Friends
    link: /friends/

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false
      comments: true
      toc: true

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    wrap: true
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
