# Site settings
title: Sang Vo Blog
email: sangvo111@example.com
name: Sang Vo
position: Ruby on Rails Developer
description: >-
  Hi, I'm Sang. I based in Da Nang,  currently work as a Backed End Engineer at Sun*.
baseurl: ""
url: ""
twitter_username: sangvo111
github_username:  sangvo

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag

include:
  - _pages

# Permalinks
permalink: /posts/:title:output_ext
paginate: 5
paginate_path: /page:num/

# Assets
sass:
  sass_dir: _sass
  style: compressed

navigation:
  - name: Home
    link: /
  - name: Articles
    link: /articles
  - name: About me
    link: /about

jekyll_compose:
  default_front_matter:
    drafts:
      description:
      image:
      category:
      tags:
    posts:
      description:
      image:
      category:
      tags:
      published: false
      sitemap: false

markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    wrap: true
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
